<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNCGIIMT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNCGIIMT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNCGIIMT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNCGIIMT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNCGIIMT\App_KernelDevDebugContainer([
    'container.build_hash' => 'NCGIIMT',
    'container.build_id' => '96328cf2',
    'container.build_time' => 1661170775,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNCGIIMT');
