<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_create_user' => [[], ['_controller' => 'App\\Controller\\CreateUserController::index'], [], [['text', '/users']], [], [], []],
    'app_list_users' => [[], ['_controller' => 'App\\Controller\\ListUsersController::index'], [], [['text', '/users']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
